//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ExtensionEnablement = global::Microsoft.VisualStudio.Modeling.Diagrams.ExtensionEnablement;
using CQRSAzure.CQRSdsl.Dsl.ExtensionEnablement;

namespace CQRSAzure.CQRSdsl.Dsl
{
	/// <summary>
	/// Partial implementation that instantiates an appropriate GestureExtensionController for this designer
	/// </summary>
	partial class CQRSdslDiagram
	{
		/// <summary>
		/// Instantiates a GestureExtensionController for this designer.
		/// </summary>
		/// <returns>IGestureExtension implementation pertinent to this designer</returns>
		protected override ExtensionEnablement::IGestureExtensionController CreateGestureExtensionController()
		{
			return new CQRSdslGestureExtensionController();
		}
	}
}

