''' <summary>
''' A record that uniquely identifies a user aggregation
''' </summary>
''' <remarks>
''' Because we allow all the data properties pertaining to a user to change but want to keep an event history 
''' of the user we use a system generated unique key integer and must connect a login to that when performing any
''' processing
''' 
''' Note: This is an example to compare against the interface generated by the CQRS.DSL.CodeGeneration created ones
''' </remarks>
Public Interface IUserAggregationIdentifier
    Inherits CQRSAzure.EventSourcing.IAggregationIdentifier(Of Integer)

End Interface
