//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CQRSAzure.CQRSdsl.Dsl
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "cqrsx";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"CQRSdsl";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"CQRSAzure";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.2.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID CQRSdslDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(CQRSdslCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID CQRSdslExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(CQRSdslCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewCQRSdslExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(CQRSdslCommandSetId), 0x0001);
	
		// Package identifier
		public const string CQRSdslPackageId = "5f54fc45-4897-47e5-b71f-8ff66160144e";
		
		// Editor factory identifier
		public const string CQRSdslEditorFactoryId = "97bf9663-c5a5-48c4-b8a4-fa384db6ea5c";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string CQRSdslModelExplorerToolWindowId = "115f2380-e1f5-418c-bcb8-bedf1ce58a28";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace CQRSAzure.CQRSdsl.Dsl
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string CQRSdslCommandSetId = "1d8f86c5-d0e9-4646-bd98-5d0bbb2fc659";
	}
}