//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using VSShellInterop = global::Microsoft.VisualStudio.Shell.Interop;
using VSShell = global::Microsoft.VisualStudio.Shell;
using DslShell = global::Microsoft.VisualStudio.Modeling.Shell;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslModeling = global::Microsoft.VisualStudio.Modeling;
using System;
using System.Diagnostics;
using System.Drawing.Design;
using System.Linq;
using System.Windows.Forms;
	
namespace CQRSAzure.CQRSdsl.Dsl
{
	/// <summary>
	/// This class implements the VS package that integrates this DSL into Visual Studio.
	/// </summary>
	[VSShell::DefaultRegistryRoot("Software\\Microsoft\\VisualStudio\\15.0")]
	[VSShell::PackageRegistration(RegisterUsing = VSShell::RegistrationMethod.Assembly, UseManagedResourcesOnly = true)]
	[VSShell::ProvideToolWindow(typeof(CQRSdslExplorerToolWindow), MultiInstances = false, Style = VSShell::VsDockStyle.Tabbed, Orientation = VSShell::ToolWindowOrientation.Right, Window = "{3AE79031-E1BC-11D0-8F78-00A0C9110057}")]
	[VSShell::ProvideToolWindowVisibility(typeof(CQRSdslExplorerToolWindow), Constants.CQRSdslEditorFactoryId)]
	[VSShell::ProvideStaticToolboxGroup("@CQRS DesignerToolboxTab;CQRSAzure.CQRSdsl.Dsl.dll", "CQRSAzure.CQRSdsl.Dsl.CQRS DesignerToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("CQRSAzure.CQRSdsl.Dsl.CQRS DesignerToolboxTab",
					"@AggregateToolToolboxItem;CQRSAzure.CQRSdsl.Dsl.dll", 
					"CQRSAzure.CQRSdsl.Dsl.AggregateToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Aggregate", 
					"@AggregateToolToolboxBitmap;CQRSAzure.CQRSdsl.Dsl.dll", 
					0xff00ff,
					Index = 0)]
	[VSShell::ProvideStaticToolboxItem("CQRSAzure.CQRSdsl.Dsl.CQRS DesignerToolboxTab",
					"@EventDefinitionToolToolboxItem;CQRSAzure.CQRSdsl.Dsl.dll", 
					"CQRSAzure.CQRSdsl.Dsl.EventDefinitionToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"EventDefinitionTool", 
					"@EventDefinitionToolToolboxBitmap;CQRSAzure.CQRSdsl.Dsl.dll", 
					0xff00ff,
					Index = 1)]
	[VSShell::ProvideStaticToolboxItem("CQRSAzure.CQRSdsl.Dsl.CQRS DesignerToolboxTab",
					"@ProjectionToolToolboxItem;CQRSAzure.CQRSdsl.Dsl.dll", 
					"CQRSAzure.CQRSdsl.Dsl.ProjectionToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ProjectionTool", 
					"@ProjectionToolToolboxBitmap;CQRSAzure.CQRSdsl.Dsl.dll", 
					0xff00ff,
					Index = 2)]
	[VSShell::ProvideStaticToolboxItem("CQRSAzure.CQRSdsl.Dsl.CQRS DesignerToolboxTab",
					"@CommandToolToolboxItem;CQRSAzure.CQRSdsl.Dsl.dll", 
					"CQRSAzure.CQRSdsl.Dsl.CommandToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"CommandTool", 
					"@CommandToolToolboxBitmap;CQRSAzure.CQRSdsl.Dsl.dll", 
					0xff00ff,
					Index = 3)]
	[VSShell::ProvideStaticToolboxItem("CQRSAzure.CQRSdsl.Dsl.CQRS DesignerToolboxTab",
					"@QueryToolToolboxItem;CQRSAzure.CQRSdsl.Dsl.dll", 
					"CQRSAzure.CQRSdsl.Dsl.QueryToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"QueryTool", 
					"@QueryToolToolboxBitmap;CQRSAzure.CQRSdsl.Dsl.dll", 
					0xff00ff,
					Index = 4)]
	[VSShell::ProvideStaticToolboxItem("CQRSAzure.CQRSdsl.Dsl.CQRS DesignerToolboxTab",
					"@ProjectionEventConnectionToolToolboxItem;CQRSAzure.CQRSdsl.Dsl.dll", 
					"CQRSAzure.CQRSdsl.Dsl.ProjectionEventConnectionToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ProjectionEvent", 
					"@ProjectionEventConnectionToolToolboxBitmap;CQRSAzure.CQRSdsl.Dsl.dll", 
					0xff00ff,
					Index = 5)]
	[VSShell::ProvideStaticToolboxItem("CQRSAzure.CQRSdsl.Dsl.CQRS DesignerToolboxTab",
					"@AggregateParenthoodConnectionToolToolboxItem;CQRSAzure.CQRSdsl.Dsl.dll", 
					"CQRSAzure.CQRSdsl.Dsl.AggregateParenthoodConnectionToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"AggregateParenthoodConnectionTool", 
					"@AggregateParenthoodConnectionToolToolboxBitmap;CQRSAzure.CQRSdsl.Dsl.dll", 
					0xff00ff,
					Index = 6)]
	[VSShell::ProvideStaticToolboxItem("CQRSAzure.CQRSdsl.Dsl.CQRS DesignerToolboxTab",
					"@IdentityGroupToolToolboxItem;CQRSAzure.CQRSdsl.Dsl.dll", 
					"CQRSAzure.CQRSdsl.Dsl.IdentityGroupToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"IdentityGroup", 
					"@IdentityGroupToolToolboxBitmap;CQRSAzure.CQRSdsl.Dsl.dll", 
					0xff00ff,
					Index = 7)]
	[VSShell::ProvideStaticToolboxItem("CQRSAzure.CQRSdsl.Dsl.CQRS DesignerToolboxTab",
					"@ClassifierToolToolboxItem;CQRSAzure.CQRSdsl.Dsl.dll", 
					"CQRSAzure.CQRSdsl.Dsl.ClassifierToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ClassifierTool", 
					"@ClassifierToolToolboxBitmap;CQRSAzure.CQRSdsl.Dsl.dll", 
					0xff00ff,
					Index = 8)]
	[VSShell::ProvideStaticToolboxItem("CQRSAzure.CQRSdsl.Dsl.CQRS DesignerToolboxTab",
					"@ClassifierEventConnectionToolToolboxItem;CQRSAzure.CQRSdsl.Dsl.dll", 
					"CQRSAzure.CQRSdsl.Dsl.ClassifierEventConnectionToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ClassifierEventConnection", 
					"@ClassifierEventConnectionToolToolboxBitmap;CQRSAzure.CQRSdsl.Dsl.dll", 
					0xff00ff,
					Index = 9)]
	[VSShell::ProvideStaticToolboxItem("CQRSAzure.CQRSdsl.Dsl.CQRS DesignerToolboxTab",
					"@ClassifierProjectionConnectionToolToolboxItem;CQRSAzure.CQRSdsl.Dsl.dll", 
					"CQRSAzure.CQRSdsl.Dsl.ClassifierProjectionConnectionToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ClassifierProjectionConnectionTool", 
					"@ClassifierProjectionConnectionToolToolboxBitmap;CQRSAzure.CQRSdsl.Dsl.dll", 
					0xff00ff,
					Index = 10)]
	[VSShell::ProvideEditorFactory(typeof(CQRSdslEditorFactory), 103, TrustLevel = VSShellInterop::__VSEDITORTRUSTLEVEL.ETL_AlwaysTrusted)]
	[VSShell::ProvideEditorExtension(typeof(CQRSdslEditorFactory), "." + Constants.DesignerFileExtension, 50)]
	[VSShell::ProvideEditorLogicalView(typeof(CQRSdslEditorFactory), "{7651A702-06E5-11D1-8EBD-00A0C90F26EA}")] // Designer logical view GUID i.e. VSConstants.LOGVIEWID_Designer
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.CSharpProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.VisualBasicProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::RegisterAsDslToolsEditor]
	[global::System.Runtime.InteropServices.ComVisible(true)]
	[DslShell::ProvideBindingPath]
	[DslShell::ProvideXmlEditorChooserBlockSxSWithXmlEditor(@"CQRSdsl", typeof(CQRSdslEditorFactory))]

	internal abstract partial class CQRSdslPackageBase : DslShell::ModelingPackage
	{
		protected global::CQRSAzure.CQRSdsl.Dsl.CQRSdslToolboxHelper toolboxHelper;	
		
		/// <summary>
		/// Initialization method called by the package base class when this package is loaded.
		/// </summary>
		protected override void Initialize()
		{
			base.Initialize();

			// Register the editor factory used to create the DSL editor.
			this.RegisterEditorFactory(new CQRSdslEditorFactory(this));
			
			// Initialize the toolbox helper
			toolboxHelper = new global::CQRSAzure.CQRSdsl.Dsl.CQRSdslToolboxHelper(this);

			// Create the command set that handles menu commands provided by this package.
			CQRSdslCommandSet commandSet = new CQRSdslCommandSet(this);
			commandSet.Initialize();
			
			// Create the command set that handles cut/copy/paste commands provided by this package.
			CQRSdslClipboardCommandSet clipboardCommandSet = new CQRSdslClipboardCommandSet(this);
			clipboardCommandSet.Initialize();
			
			// Register the model explorer tool window for this DSL.
			this.AddToolWindow(typeof(CQRSdslExplorerToolWindow));

			// Initialize Extension Registars
			// this is a partial method call
			this.InitializeExtensions();

			// Add dynamic toolbox items
			this.SetupDynamicToolbox();
		}

		/// <summary>
		/// Partial method to initialize ExtensionRegistrars (if any) in the DslPackage
		/// </summary>
		partial void InitializeExtensions();
		
		/// <summary>
		/// Returns any dynamic tool items for the designer
		/// </summary>
		/// <remarks>The default implementation is to return the list of items from the generated toolbox helper.</remarks>
		protected override global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			try
			{
				Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
				return toolboxHelper.CreateToolboxItems();
			}
			catch(global::System.Exception e)
			{
				global::System.Diagnostics.Debug.Fail("Exception thrown during toolbox item creation.  This may result in Package Load Failure:\r\n\r\n" + e);
				throw;
			}
		}
		
		
		/// <summary>
		/// Given a toolbox item "unique ID" and a data format identifier, returns the content of
		/// the data format. 
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve data for</param>
		/// <param name="format">The desired format of the resulting data</param>
		protected override object GetToolboxItemData(string itemId, DataFormats.Format format)
		{
			Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
		
			// Retrieve the specified ToolboxItem from the DSL
			return toolboxHelper.GetToolboxItemData(itemId, format);
		}
	}

}

//
// Package attributes which may need to change are placed on the partial class below, rather than in the main include file.
//
namespace CQRSAzure.CQRSdsl.Dsl
{
	/// <summary>
	/// Double-derived class to allow easier code customization.
	/// </summary>
	[VSShell::ProvideMenuResource("1000.ctmenu", 1)]
	[VSShell::ProvideToolboxItems(1)]
	[global::Microsoft.VisualStudio.TextTemplating.VSHost.ProvideDirectiveProcessor(typeof(global::CQRSAzure.CQRSdsl.Dsl.CQRSdslDirectiveProcessor), global::CQRSAzure.CQRSdsl.Dsl.CQRSdslDirectiveProcessor.CQRSdslDirectiveProcessorName, "A directive processor that provides access to CQRSdsl files")]
	[global::System.Runtime.InteropServices.Guid(Constants.CQRSdslPackageId)]
	internal sealed partial class CQRSdslPackage : CQRSdslPackageBase
	{
	}
}