//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ExtensionEnablement = global::Microsoft.VisualStudio.Modeling.ExtensionEnablement;

namespace CQRSAzure.CQRSdsl.Dsl.ExtensionEnablement
{ 
	/// <summary>
	/// ExtensionRegistrar base class to register validation extensions 
	/// </summary>	
	internal abstract class CQRSdslValidationExtensionRegistrarBase : ExtensionEnablement::ValidationExtensionRegistrar
	{
		/// <summary>
		/// This registrar will filter out validation methods that do not provide an item of metadata with this value as its key.
		/// </summary>
		protected override global::System.String MetadataFilter
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return global::CQRSAzure.CQRSdsl.Dsl.ExtensionEnablement.CQRSdslExtensionFilter.MefMetadataFilter;
			}
		}
	}
	
	/// <summary>
	/// ExtensionRegistrar to register Validation extensions.
	/// </summary>
	/// <remarks>
	/// Double-derived to allow customizations by Dsl Authors.
	/// </remarks>	
	internal partial class CQRSdslValidationExtensionRegistrar : CQRSdslValidationExtensionRegistrarBase
	{		
	}
}