//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounts.Account.identitygroup
{
    using System;
    using CQRSAzure.EventSourcing;
    using Accounts.Account;
    
    
    /// <summary>
    /// Accounts with a non-zero balance
    /// </summary>
    [CQRSAzure.EventSourcing.DomainNameAttribute("Accounts")]
    [CQRSAzure.EventSourcing.Category("Financial")]
    public partial class Accounts_In_Credit : object, IAccounts_In_Credit
    {
        
        /// <summary>
        /// Empty constructor for serialisation
        /// This should be removed if serialisation is not needed
        /// </summary>
        Accounts_In_Credit()
        {
        }
    }
}
