//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CQRSAzure.IdentifierGroup;
using Accounts.Account.eventDefinition;

/// <remarks>
/// Only open accounts may have transactions recorded, interest and so on
/// </remarks>
namespace Accounts.Account.classifier
{



    /// <summary>
    /// Classify those accounts that are currently open
    /// </summary>
    /// <remarks>
    /// Only open accounts may have transactions recorded, interest and so on
    /// </remarks>
    [CQRSAzure.EventSourcing.DomainNameAttribute("Accounts")]
    [CQRSAzure.EventSourcing.Category("Accounts")]
    public partial class Account_Open_Classifier : object, IAccount_Open_Classifier
    {
        
        /// <summary>
        /// Empty constructor for serialisation
        /// This should be removed if serialisation is not needed
        /// </summary>
        public Account_Open_Classifier()
        {
        }
        
        /// <summary>
        /// The account was closed
        /// </summary>
        public IClassifierDataSourceHandler.EvaluationResult EvaluateEvent(IClosed eventToEvaluate)
        {
            // On Closed,  always set to Exclude
            return IClassifierDataSourceHandler.EvaluationResult.Exclude;
        }
        
        /// <summary>
        /// New account was opened
        /// </summary>
        public IClassifierDataSourceHandler.EvaluationResult EvaluateEvent(IOpened eventToEvaluate)
        {
            // On Opened,  always set to Include
            return IClassifierDataSourceHandler.EvaluationResult.Include;
        }
    }
}
