//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounts.Account.commandDefinition
{
    using System;
    using CQRSAzure.EventSourcing;
    using CQRSAzure.CommandDefinition;
    using Accounts.Account;
    
    
    /// <summary>
    /// Apply interest to each open account
    /// </summary>
    /// <remarks>
    /// This is run as an "overnight" batch process
    /// </remarks>
    [CQRSAzure.EventSourcing.DomainNameAttribute("Accounts")]
    [CQRSAzure.EventSourcing.Category("Financial")]
    [CQRSAzure.EventSourcing.IdentityGroup()]
    public partial class Apply_Interest_Definition : CommandDefinitionBase, IApply_Interest_Definition
    {
        
        /// <summary>
        /// The unique name of this command
        /// Apply Interest
        /// </summary>
        public override string CommandName
        {
            get
            {
                return "Apply Interest";
            }
        }
        
        /// <summary>
        /// Apply interest to all the open accounts
        /// </summary>
        public double Interest_Rate
        {
            get
            {
                return base.GetParameterValue<double>("Interest Rate", 0);
            }
            set
            {
                base.SetParameterValue("Interest Rate", 0, ref value);
            }
        }
    }
}
