//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounts.Account.commandHandler
{
    using CQRSAzure.EventSourcing;
    using CQRSAzure.CommandDefinition;
    using CQRSAzure.CommandHandler;
    using Accounts.Account;
    using Accounts.Account.commandDefinition;
    
    
    /// <summary>
    /// Apply interest to each open account
    /// </summary>
    /// <remarks>
    /// This is run as an "overnight" batch process
    /// </remarks>
    [CQRSAzure.EventSourcing.DomainNameAttribute("Accounts")]
    [CQRSAzure.EventSourcing.Category("Financial")]
    public partial class Apply_Interest_Handler : CommandHandlerBase<IApply_Interest_Definition>, IApply_Interest_Handler
    {
        
        /// <summary>
        /// Handle the command definition
        /// Apply interest to each open account
        /// </summary>
        /// <param name="cmdToHandle">
        /// The instance of the command definition to handle
        /// </param>
        public override void HandleCommand(IApply_Interest_Definition cmdToHandle)
        {
            // TODO : Process the command definition passed in
        }
    }
}
