//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounts.Account.queryHandler
{
    using CQRSAzure.EventSourcing;
    using CQRSAzure.QueryDefinition;
    using CQRSAzure.QueryHandler;
    using System.Collections.Generic;
    using Accounts.Account;
    using Accounts.Account.queryDefinition;
    
    
    /// <summary>
    /// Get the current balance for open accounts
    /// </summary>
    /// <remarks>
    /// Retrieves the account balances for all open accounts
    /// </remarks>
    [CQRSAzure.EventSourcing.DomainNameAttribute("Accounts")]
    [CQRSAzure.EventSourcing.Category("Financial")]
    public partial class Get_Open_Account_Balances_Handler : QueryHandlerBase<IGet_Open_Account_Balances_Definition, IGet_Open_Account_Balances__Return>, IGet_Open_Account_Balances_Handler
    {
        
        /// <summary>
        /// Handle the query definition
        /// Get the current balance for open accounts
        /// </summary>
        /// <param name="qryToHandle">
        /// The instance of the query definition to handle and return data for
        /// </param>
        public override IEnumerable<IGet_Open_Account_Balances_Definition_Return> HandleQuery(IGet_Open_Account_Balances_Definition qryToHandle)
        {
            IEnumerable<IGet_Open_Account_Balances_Definition_Return> queryReturn = null;
            // TODO : Populate the query return value
            return queryReturn;
        }
    }
}
