//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Accounts.Account.eventDefinition;

namespace Accounts.Account.classifier
{


    /// <summary>
    /// Classify those accounts that are currently open
    /// </summary>
    /// <remarks>
    /// Only open accounts may have transactions recorded, interest and so on
    /// </remarks>
    public partial interface IAccount_Open_Classifier : 
        CQRSAzure.IdentifierGroup.IClassifierEventHandler<IClosed>, 
        CQRSAzure.IdentifierGroup.IClassifierEventHandler<IOpened>
    {
    }
}
