//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounts.Account.identitygroup
{


    /// <summary>
    /// Accounts with a non-zero balance
    /// </summary>
    public partial interface IAccounts_In_Credit
        : CQRSAzure.IdentifierGroup.IIdentifierGroup<Account  >
    {


    }
}
