//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CQRSAzure.EventSourcing;
using Accounts.Account;

namespace Accounts.Account.eventDefinition
{



    /// <summary>
    /// The account was closed
    /// </summary>
    public partial interface IClosed 
        : IEvent<IAccount>
    {
        
        /// <summary>
        /// The date as of which the account was closed
        /// </summary>
        System.DateTime Date_Closed
        {
            get;
        }
        
        /// <summary>
        /// Why the account was closed
        /// </summary>
        string Reason
        {
            get;
        }
    }
}
