//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CQRSAzure.EventSourcing;
using Accounts.Account;

namespace Accounts.Account.eventDefinition
{


    /// <summary>
    /// Money was depositted in the account
    /// </summary>
    public partial interface IMoney_Deposited : IEvent<IAccount>
    {
        
        /// <summary>
        /// The amount deposited (in base currency)
        /// </summary>
        decimal Amount
        {
            get;
        }
        
        /// <summary>
        /// The date the deposit was made
        /// </summary>
        System.DateTime Date_Deposited
        {
            get;
        }
        
        /// <summary>
        /// The date applied to the account
        /// </summary>
        /// <remarks>
        /// The deposit does not affect the balance until it is applied
        /// </remarks>
        System.DateTime Date_Applied
        {
            get;
        }
        
        /// <summary>
        /// Deposit currency code
        /// </summary>
        /// <remarks>
        /// ISO (3 letter) currency code if the deposit was in a non-base currency
        /// </remarks>
        string Exchange_Currency
        {
            get;
        }
        
        /// <summary>
        /// Exchange rate applied to the deposit
        /// </summary>
        /// <remarks>
        /// This will be 1.0 if in base currency
        /// </remarks>
        decimal Exchange_Rate
        {
            get;
        }
    }
}
