//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounts.Account.identitygroup
{


    /// <summary>
    /// The set of currently open accounts
    /// </summary>
    /// <remarks>
    /// This is the full set of active open accounts that can have transactions posted to them
    /// </remarks>
    public partial interface IOpen_Accounts
    {
    }
}
