//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using CQRSAzure.EventSourcing;
using Accounts.Account;

namespace Accounts.Account.eventDefinition
{



    /// <summary>
    /// New account was opened
    /// </summary>
    public partial interface IOpened 
        : IEvent<IAccount>
    {
        
        /// <summary>
        /// The date from which the account is active
        /// </summary>
        /// <remarks>
        /// An event stream may have more than one opened event, if it was closed and re-opened for example
        /// </remarks>
        System.DateTime Date_Opened
        {
            get;
        }
        
        /// <summary>
        /// The currency of the account
        /// </summary>
        /// <remarks>
        /// ISO (3 letter) currency codes
        /// </remarks>
        string Base_Currency
        {
            get;
        }
    }
}
