//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using CQRSAzure.EventSourcing;
using Accounts.Account.eventDefinition;

namespace Accounts.Account.projection
{



    /// <summary>
    /// The running balance of the account
    /// </summary>
    public partial interface IRunning_Balance : IProjection<Account, string>, 
        CQRSAzure.EventSourcing.IHandleEvent<Money_Deposited>, 
        CQRSAzure.EventSourcing.IHandleEvent<Money_Withdrawn>
    {
        
        /// <summary>
        /// The date/time of the last balance affecting transaction
        /// </summary>
        System.DateTime Last_Transaction_Date
        {
            get;
        }
        
        /// <summary>
        /// The account balance
        /// </summary>
        decimal Balance
        {
            get;
        }
    }
}
