//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Runtime.Serialization;

namespace Accounts.Account.eventDefinition
{


    /// <summary>
    /// New account was opened
    /// </summary>
    [Serializable()]
    [CQRSAzure.EventSourcing.DomainNameAttribute("Accounts")]
    [CQRSAzure.EventSourcing.EventAsOfDateAttribute("Date_Opened")]
    public partial class Opened 
        : object, 
        IOpened, 
        CQRSAzure.EventSourcing.IEvent<Account > 
    {
        
        // Version number - always increment this if the event definition changes
        public const int EVENT_VERSION = 0;
        
        #region Private members
        // TODO: Make this property read only
        private System.DateTime _Date_Opened;
        
        // TODO: Make this property read only
        private string _Base_Currency;
        #endregion
        
        /// <summary>
        /// Empty constructor For serialisation
        /// This should be removed If serialisation Is Not needed
        /// </summary>
        public Opened()
        {
        }
        
        /// <summary>
        /// Create And populate a New instance Of this Class from the underlying Interface
        /// </summary>
        /// <remarks>
        /// This should be called When the Event Is created from an Event stream
        /// </remarks>
        public Opened(IOpened OpenedInit)
        {
            _Date_Opened = OpenedInit.Date_Opened;
            _Base_Currency = OpenedInit.Base_Currency;
        }
        
        /// <summary>
        /// Create And populate a New instance Of this Class from the underlying properties
        /// </summary>
        /// <remarks>
        /// This should be called When the Event Is created from an Event stream
        /// </remarks>
        /// <param name="Date Opened">
        /// The date from which the account is active
        /// An event stream may have more than one opened event, if it was closed and re-opened for example
        /// </param>
        /// <param name="Base Currency">
        /// The currency of the account
        /// ISO (3 letter) currency codes
        /// </param>
        public Opened(System.DateTime Date_Opened_In, string Base_Currency_In)
        {
            _Date_Opened = Date_Opened_In;
            _Base_Currency = Base_Currency_In;
        }
        
        /// <summary>
        /// Create And populate a New instance Of this Class from the serialized data
        /// </summary>
        /// <param name="info">
        /// The SerializationInfo passed In containing the values Of this Event
        /// </param>
        /// <param name="context">
        /// Additional StreamingContext On how the Event Is streamed
        /// </param>
        Opened(SerializationInfo info, StreamingContext context)
        {
            _Date_Opened = info.GetDateTime("Date_Opened");
            _Base_Currency = info.GetString("Base_Currency");
        }
        
        public uint Version
        {
            get
            {
                return EVENT_VERSION;
            }
        }
        
        /// <summary>
        /// The date from which the account is active
        /// </summary>
        /// <remarks>
        /// An event stream may have more than one opened event, if it was closed and re-opened for example
        /// </remarks>
        public System.DateTime Date_Opened
        {
            get
            {
                return _Date_Opened;
            }
        }
        
        /// <summary>
        /// The currency of the account
        /// </summary>
        /// <remarks>
        /// ISO (3 letter) currency codes
        /// </remarks>
        public string Base_Currency
        {
            get
            {
                return _Base_Currency;
            }
        }
        
        /// <summary>
        /// Factory method To create an instance Of this Event
        /// </summary>
        /// <param name="Date Opened">
        /// The date from which the account is active
        /// An event stream may have more than one opened event, if it was closed and re-opened for example
        /// </param>
        /// <param name="Base Currency">
        /// The currency of the account
        /// ISO (3 letter) currency codes
        /// </param>
        static IOpened Create(System.DateTime Date_Opened_In, string Base_Currency_In)
        {
            return new Opened(Date_Opened_In, Base_Currency_In);
        }
        
        /// <summary>
        /// Populates a SerializationInfo with the data needed to serialize this event instance
        /// </summary>
        /// <remarks>
        /// The version number is also to be saved
        /// </remarks>
        public void GetObjectData(SerializationInfo info, StreamingContext context)
        {
            info.AddValue("Date_Opened", _Date_Opened);
            info.AddValue("Base_Currency", _Base_Currency);
            info.AddValue("EVENT_VERSION", EVENT_VERSION);
        }
    }
}
