//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.Serialization;

namespace Accounts.Account.eventDefinition
{



    /// <summary>
    /// New account was opened
    /// </summary>
    public partial class Opened
    {
        
        /// <summary>
        /// Method called during the serialising process
        /// </summary>
        /// <remarks>
        /// Any changes to the standard way that the event instance is serialised should go here
        /// In which case you should add a [NonSerialized] attribute to any members you want to override the serialisation of
        /// </remarks>
        [OnSerializing()]
        public void OnSerializingMethod(System.Runtime.Serialization.StreamingContext context)
        {
        }
        
        /// <summary>
        /// Method called after the completion the serialising process
        /// </summary>
        /// <remarks>
        /// Any resetting of parameters after they are serialised should go here
        /// </remarks>
        [OnSerialized()]
        public void OnSerializedMethod(System.Runtime.Serialization.StreamingContext context)
        {
        }
        
        /// <summary>
        /// Method called during the deserialising process
        /// </summary>
        /// <remarks>
        /// Any manipulation of properties as they are deserialized should go here
        /// </remarks>
        [OnDeserializing()]
        public void OnDeserializingMethod(System.Runtime.Serialization.StreamingContext context)
        {
        }
        
        /// <summary>
        /// Method called after the deserialising process completes
        /// </summary>
        /// <remarks>
        /// Any manipulation of properties after they are deserialized should go here
        /// </remarks>
        [OnDeserialized()]
        public void OnDeserializedMethod(System.Runtime.Serialization.StreamingContext context)
        {
        }
    }
}
