Imports CQRSAzure.EventSourcing
''' <summary>
''' A class to give the aggregagion identifier for a user
''' </summary>
''' <remarks>
''' Each user is identified by an unique integer, padded to 10 digits width 
''' 
''' Note: This is an example to compare against the interface generated by the CQRS.DSL.CodeGeneration created ones
''' </remarks>
<AggregateIdentifierAttribute(GetType(IUserAggregationIdentifier))>
Public Class UserAggregationidentifier
    Implements IUserAggregationIdentifier

    Private Const USERID_FORMAT As String = "0000000000" 'MaxInt = 2,147,483,647
    Private m_key As Integer

    Public Function GetAggregateIdentifier() As String Implements CQRSAzure.EventSourcing.IAggregationIdentifier.GetAggregateIdentifier
        Return m_key.ToString(USERID_FORMAT)
    End Function

    Public Sub SetKey(key As Integer) Implements CQRSAzure.EventSourcing.IAggregationIdentifier(Of Integer).SetKey
        m_key = key
    End Sub

    Public Sub New(ByVal key As Integer)
        m_key = key
    End Sub

    Public Function GetKey() As Integer Implements IAggregationIdentifier(Of Integer).GetKey
        Return m_key
    End Function
End Class
